@baseUrl = http://localhost:3000


### Health
# GET {{baseUrl}}/health
# Accept: application/json

POST {{baseUrl}}/api/usuarios
Content-Type: application/json

{
    "name": "putin",
    "email": "niggermaxer@gmail.com",
    "nivel": "basico"
}
