### Base URL
@baseUrl = http://localhost:3000/api
@baseUrlUploads = http://localhost:3000/uploads
@testMovieId = 69a18201af7366314ba02fd6

### Listar películas
GET {{baseUrl}}/movies

### Obtener película por ID
GET {{baseUrl}}/movies/{{testMovieId}}

### Crear película
POST {{baseUrl}}/movies
Content-Type: application/json

{
  "title": "Example Movie",
  "director": "Jane Doe",
  "year": 2020,
  "genre": "drama",
  "copies": 3,
  "availableCopies": 3
}

### Actualizar película
PUT {{baseUrl}}/movies/{{testMovieId}}
Content-Type: application/json

{
  "title": "Example Movie Updated"
}

### Eliminar película
DELETE {{baseUrl}}/movies/{{testMovieId}}

### Alquilar película
POST {{baseUrl}}/movies/{{testMovieId}}/rent

### Devolver película
POST {{baseUrl}}/movies/{{testMovieId}}/return

### Subir carátula (usar curl para multipart)
# curl -X PATCH http://localhost:3000/api/movies/id/cover -F "file=@C:\workspace\foton.jpg"

### Obtener carátula por movie id (devuelve la imagen directamente)
GET {{baseUrl}}/movies/{{testMovieId}}/cover

### Obtener carátula por filename
GET {{baseUrlUploads}}/file-1772190442350-174076269.jpg

### Top películas
GET {{baseUrl}}/movies/stats/top

### Películas disponibles
GET {{baseUrl}}/movies/available

### Puntuar película
POST {{baseUrl}}/movies/{{testMovieId}}/rate
Content-Type: application/json

{
  "rating": 5
}
